catalog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
import uuid
from django.conf.urls import url
from . import views as core_views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
	path('events/', views.EventListView.as_view(), name='events'),
	path('events/<int:pk>', views.EventDetailView.as_view(), name='event-detail'),
    path('venue/<int:pk>', views.VenueDetailView.as_view(), name='venue-detail'),

    path('myinvits/', views.InvitedListView.as_view(), name='my-invited'),
    path('myinvits/<uuid:pk>', views.InvitedDetailView.as_view(), name='invite-detail'),
    path('myorganized/', views.OrganizedListView.as_view(), name='my-organized'),
    path('user/<int:pk>', views.UserDetailView.as_view(), name='profile'),

    path('events/create/', views.EventCreate.as_view(), name = 'events_create'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='events_update'),
    path('events/<int:pk>/delete', views.EventDelete.as_view(), name='events_delete'),

    path('invitations/create/', views.InviteCreate.as_view(), name='invite_create'),
    path('invitations/<uuid:pk>/update/', views.InviteUpdate.as_view(), name='invite_update'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nimantran/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from catalog import views as core_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
	path('accounts/', include('django.contrib.auth.urls')),
    url(r'^signup/$', core_views.signup, name='signup'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Category(models.Model):
    """
    Model representing the category of an event i.e. Marriage, Birthday, Obituary etc.
    """
    name = models.CharField(max_length=200, help_text = "Enter an event cateory(e.g. Marriage, Birthday etc.)")

    def __str__(self):
        return self.name

class People(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.IntegerField(help_text = "Person's phone number")
    dob = models.DateField(null = True, help_text = "Date of Birth")
    email = models.EmailField(help_text = "Email id")

    class Meta:
        ordering = ["last_name", "first_name"]
        permissions = (("can_mark_going", "Set event as going"),)

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('people-detail', args = [str(self.id)])

class Venue(models.Model):
    name = models.CharField(max_length = 200)
    address = models.CharField(max_length = 500, help_text = "address of the venue")
    capacity = models.IntegerField(help_text = "Maximum capacity of the venue")
    lat = models.DecimalField(help_text = "Latitude for the venue", null=True, blank=True, max_digits=10, decimal_places=7)
    lng = models.DecimalField(help_text = "Longitude for the venue", null=True, blank=True, max_digits=10, decimal_places=7)

    def __str__(self):
        return self.name

class Event(models.Model):
    """
    Model representing the event
    """
    title = models.CharField(max_length = 200, help_text = "Provide a title to your event.")
    description = models.CharField(max_length = 500, help_text = "Briefly describe in 500 chars.")
    dateFrom = models.DateField()
    dateTo = models.DateField()
    organizer = models.ForeignKey(User, on_delete = models.SET_NULL, null=True, blank=True)
    cateory = models.ManyToManyField(Category, help_text = "Select a category for this event")
    venue = models.ForeignKey(Venue, help_text = "Select the venue", on_delete = models.DO_NOTHING)
    public = models.BooleanField(default = True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('event-detail', args=[str(self.id)])

    def display_category(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ cateory.name for category in self.cateory.all()[:3] ])

class Invitation(models.Model):
    """
    Model representing each invite
    """
    id = models.UUIDField(primary_key = True, default = uuid.uuid4, help_text = "Unique ID for this invite")
    event = models.ForeignKey(Event, help_text = "select the event for this invitation", on_delete = models.DO_NOTHING)
    invitee = models.ForeignKey(User, on_delete = models.SET_NULL, null=True, blank=True)
    note = models.CharField(max_length = 1000, help_text = "A personalised note for the guest", null = True)

    INVITE_STATUS = (
        ('i', 'Interested'),
        ('g', 'Going'),
        ('n', 'Not going'),
    )

    status = models.CharField(max_length = 1, choices = INVITE_STATUS, default = 'n', help_text = 'Interest in the event')

    def __str__(self):
        return '{0} ({1})'.format(self.id, self.event.title)

    def get_absolute_url(self):
        return reverse('invite-detail', args=[str(self.id)])

catalog/forms.py
from django import forms

class SelectResponse(forms.Form):
    new_status = forms.CharField(label='New Status', max_length=1)

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Event

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.
from .models import People, Venue, Event, Invitation
from .forms import SelectResponse

from django.views import generic

def index(request):
    """
    View function for homepage
    """
    # generating counts of the some main objects
    num_people = User.objects.all().count()
    num_venue = Venue.objects.all().count()
    num_event = Event.objects.all().count()

    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    # render the html template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={'num_people':num_people, 'num_venue':num_venue, 'num_event':num_event, 'num_visits':num_visits},
    )

def about(request):
    """
    View function for about page
    """

    return render(
        request,
        'about.html',
    )

class EventListView(generic.ListView):
    model = Event

class EventDetailView(generic.DetailView):
    model = Event

class VenueDetailView(generic.DetailView):
    model = Venue

class InvitedListView(LoginRequiredMixin, generic.ListView):
    model = Invitation
    template_name = 'catalog/invited_list_user.html'

    def get_queryset(self):
        return Invitation.objects.filter(invitee=self.request.user)

class InvitedDetailView(LoginRequiredMixin, generic.DetailView):
    model = Invitation
    template_name = 'catalog/invitation_detail.html'

class OrganizedListView(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = 'catalog/organized_list_user.html'

    def get_queryset(self):
        return Event.objects.filter(organizer=self.request.user)

from django.contrib.auth.decorators import permission_required

@permission_required('catalog.can_mark_going')
@permission_required('catalog.can_edit')
def my_view(request):

    from django.contrib.auth.mixins import PermissionRequiredMixin

    class MyView(PermissionRequiredMixin, View):
        permission_required = 'catalog.can_mark_going'
        # Or multiple permissions
        permission_required = ('catalog.can_mark_going', 'catalog.can_edit')
        # Note that 'catalog.can_edit' is just an example
        # the catalog application doesn't have such permission!

class UserDetailView(generic.DetailView):
    model = User
    
class UserDetailView(generic.DetailView):
    model = User
    template_name = 'catalog/user_detail.html'

class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    fields = '__all__'

class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    fields = '__all__'

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('events')

class InviteUpdate(LoginRequiredMixin, UpdateView):
    model = Invitation
    fields = ['status']

class InviteCreate(LoginRequiredMixin, CreateView):
    model = Invitation
    fields = ['event', 'invitee', 'note']

class InvitationCreate(LoginRequiredMixin, CreateView):
    model = Invitation
    fields = ['event', 'invitee', 'note']

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

catalog/templates/catalog/event_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>{{ event.title }}</h1>
    <hr>
    <div>
        <div style="display: inline-block; margin: 0px; padding: 0px;">
            <p><strong>Description:</strong> {{ event.description }}</p>
            <p><strong>Date from:</strong> {{ event.dateFrom }}</p>
            <p><strong>Date to:</strong> {{ event.dateTo }}</p>
            <p><strong>Category:</strong> {% for cateory in event.cateory.all %} <span style="border-radius: 20px; background-color: #17A589; color: white; padding: 8px; width: auto">{{ cateory }}</span>{% if not forloop.last %} {% endif %}{% endfor %}</p>
            <p><strong>Public:</strong> {{ event.public }}</p>
        </div>
        <center><a class="card" href="{% url 'profile' event.organizer.pk %}"><strong>Organizer:</strong> {{ event.organizer.first_name }} {{ event.organizer.last_name }}</a>
        <a class="card" href="{% url 'venue-detail' event.venue.pk %}"><strong>Venue: </strong>{{ event.venue }}</a></center>
    </div>

    {% if user == event.organizer %}
        <center>
        <h4>Invitations</h4>
        <hr>
        <div style="vertical-align:top;">

            <div class="card-display">
                <div style="text-transform: uppercase; font-weight: bold; vertical-align:top;" class="text-success">going</div>
                <hr style="border: 1px solid #85C1E9!important">
                {% for invite in event.invitation_set.all %}
                {% if invite.status == 'g' %}
                    <div style="color:white"><strong>{{ invite.invitee.first_name }} {{ invite.invitee.last_name }}</strong></div>
                {% endif %}
                {% endfor %}
            </div>

            <div class="card-display">
                <div style="text-transform: uppercase; font-weight: bold; vertical-align:top;" class="text-warning">interested</div>
                <hr style="border: 1px solid #85C1E9!important">
                {% for invite in event.invitation_set.all %}
                {% if invite.status == 'i' %}
                    <div style="color:white"><strong>{{ invite.invitee.first_name }} {{ invite.invitee.last_name }}</strong></div>
                {% endif %}
                {% endfor %}
            </div>

            <div class="card-display">
                <div style="text-transform: uppercase; font-weight: bold; vertical-align:top;" class="text-danger">not going</div>
                <hr style="border: 1px solid #85C1E9!important">
                {% for invite in event.invitation_set.all %}
                {% if invite.status == 'n' %}
                    <div style="color:white"><strong>{{ invite.invitee.first_name }} {{ invite.invitee.last_name }}</strong></div>
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <a class="card-display" href="/catalog/invitations/create/" style="color: white; background-color: #2ECC71; ">
            <strong>+ NEW INVITE</strong>
        </a></center>
    {% else %}

    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/event_form.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <center>
    <h1>Create event</h1>
    <hr>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <hr>
        <hr>
        <br>
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/event_list.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>Event List</h1>
    <hr>
    <div class="outer">
    {% if event_list %}
      {% for event in event_list %}
          <a class="card" href="{{ event.get_absolute_url }}">
              <h3>{{ event.title }}</h3>
              ({{event.dateTo}}) ({{event.venue.name}})
          </a>
      {% endfor %}
    {% else %}
      <p>There are no events.</p>
    {% endif %}
  </div>
</div>

{% endblock %}

catalog/templates/catalog/invitation_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>{{ invitation.event.title }} - by {{ invitation.event.organizer.first_name }} {{ invitation.event.organizer.last_name }}</h1>
    <hr>
    <div style="margin: 0px; padding: 0px;">
        <div>
            <center><div class="card-display" style="background-color: #148F77; color: white"><strong>DATE FROM</strong><br><hr> {{ invitation.event.dateFrom }}</div>
            <div class="card-display" style="color: white; background-color: #148F77"><strong>DATE TO</strong><br><hr> {{ invitation.event.dateTo }}</div>
            <a href="{% url 'venue-detail' invitation.event.venue.pk %}" class="card-display" style="color: white; background-color: #E74C3C;"><strong>VENUE </strong><br><hr> {{ invitation.event.venue }}</a></center>
        </div>
        <br>

        <center><div><strong>DESCRIPTION:</strong><hr> {{ invitation.event.description }}</div></center>
        <br>

        <div>
            <center><div style="display: inline-block; margin-right:20px; width: 200px;"><strong>CATEGORY:</strong><hr> {% for cateory in invitation.event.cateory.all %} <span style="border-radius: 20px; background-color: #17A589; color: white; padding: 8px; width: auto">{{ cateory }}</span> {% if not forloop.last %} {% endif %}{% endfor %}</div>
            <div style="display: inline-block; width: 200px;"><strong>PUBLIC:</strong><hr> {{ invitation.event.public }}</div></center>
        </div>
        <br>

        <center><div><strong>MESSAGE:</strong><hr> {{ invitation.note }}</div></center>
        <br>

        <div>
            <center><div class="card-display" style="background-color: #dc3545; color: white"><strong>NOT GOING {% if invitation.status == 'n' %}&#10003;{% endif %}</strong></div>
            <div class="card-display" style="color: white; background-color: #ffc107"><strong>INTERESTED {% if invitation.status == 'i' %}&#10003;{% endif %}</strong></div>
            <div class="card-display" style="color: white; background-color: #28a745;"><strong>GOING {% if invitation.status == 'g' %}&#10003;{% endif %}</strong></div></center>
        </div>

        <center><a class="card-display" href="/catalog/invitations/{{ invitation.id }}/update" style="color: white; background-color: #2C3E50; border-radius: 50%; height: 100px; width: 100px; padding-top: 37px;">
            <strong>CHANGE</strong>
        </a></center>

        <br>

    </div>
</div>
{% endblock %}

catalog/templates/catalog/invitation_form.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <center>
    <h1>Invitation</h1>
    <hr>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <br>
        <hr>
        <h5>This event is created by: {{ user }}</h5>
        <hr>
        <br>
        <input type="submit" value="Submit"/>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/invited_list_user.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>Invitations</h1>
    <hr>

    <div class="outer">
      {% if invitation_list %}

        {% for invite in invitation_list %}
        <a href="{{ invite.get_absolute_url }}" class="card">
              <h3>{{invite.event.title}}</h3> ({{ invite.event.dateFrom }})
        </a>
        {% endfor %}

      {% else %}
        <p>There are no current invitations.</p>
      {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/organized_list_user.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>My Events</h1>
    <hr>
    <div class="outer">
      {% if event_list %}
        {% for event in event_list %}
        <a class="card" href="{{ event.get_absolute_url }}">
            <h3>{{ event.title }}</h3>
            ({{event.dateFrom}})
        </a>
        {% endfor %}

      {% else %}
        <p>You have no events.</p>
      {% endif %}
    </div>
    <center><a class="card-display" href="/catalog/events/create/" style="color: white; background-color: #2ECC71; ">
        <strong>+ NEW EVENT</strong>
    </a></center>
</div>
{% endblock %}

catalog/templates/catalog/user_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <div style="padding: 3%">
      <h1>{{ user.first_name }} {{ user.last_name }}</h1>
      <hr>
      <div>
          {% load static %}
          <img src="{% static "catalog/avatar.jpg" %}" class="card-display" alt="avatar" style="padding:0px; height: 200px; width: auto; border-radius: 50%"/>

          <div style="display: inline-block; margin: 0px; padding: 0px;">
              <p><strong>Username:</strong> {{ user.username }}</p>
              <p><strong>E-mail:</strong> {{ user.email }}</p>
          </div>
      </div>

      <br>
      <h4>Events organised by {{ user.first_name }}:</h4>
      <hr>
      <div class="outer">
        {% for event in user.event_set.all %}
            <a class="card" href="{{ event.get_absolute_url }}">
                <h3>{{ event.title }}</h3>
                ({{event.dateTo}}) ({{event.venue.name}})
            </a>
        {% endfor %}
    </div>
  </div>

{% endblock %}

catalog/templates/catalog/venue_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="padding: 3%">
    <h1>{{ venue.name }}</h1>
    <hr>
    <p><strong>Address:</strong> {{ venue.address }}</p>
    <p><strong>Capacity:</strong> {{ venue.capacity }}</p>

    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"></script>
    <script src="custom.js"></script>

	<div id="map" style="width:100%; height:500px; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); border: solid 1px black"></div>

	<script>
    	function myMap() {
            var myCenter = new google.maps.LatLng({{ venue.lat }}, {{ venue.lng }});
            var mapCanvas = document.getElementById("map");
            var mapOptions = {center: myCenter, zoom: 15};
            var map = new google.maps.Map(mapCanvas, mapOptions);
            var marker = new google.maps.Marker({
                position:myCenter,
                animation: google.maps.Animation.BOUNCE
            });
            marker.setMap(map);
            var infowindow = new google.maps.InfoWindow({
                content: "{{ venue.name }}<br>{{ venue.address }}"
              });
              infowindow.open(map,marker);
    	}
	</script>

	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAqFOY1AP0p8NWr7TLCr68AIAWlFepwMj4&callback=myMap"></script>

    <br>
    <h4>Events organised here:</h4>
    <hr>

    <div class="outer">
        {% for event in venue.event_set.all %}
        <a class="card" href="{{ event.get_absolute_url }}">
            <h3>{{ event.title }}</h3>
            ({{event.dateTo}}) ({{event.venue.name}})
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}